# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'iBeauty' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  # Pods for iBeauty
  
end

target 'iBeautyTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'iBeautyUITests' do
  inherit! :search_paths
  # Pods for testing
end


